services:
  postgres-test:
    image: postgres:17

    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  kong:
    image: kong:3.9
    ports:
      - "8000:8000"
      - "8001:8001"

    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr

    volumes:
      - ./gateway/kong.yml:/kong/declarative/kong.yml:ro

    depends_on:
      api:
        condition: service_started

  api:
    build:
      context: .
      target: development

    volumes:
      - .:/app

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_password
      POSTGRES_DB: backend_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend_user -d backend_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
